
package project;

import javax.swing.JOptionPane;
import project.logic.Administrador;


public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    Administrador myadiministrador;
    public LogIn(Administrador myList) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.myadiministrador = myList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jblNickname = new javax.swing.JLabel();
        jblPassword = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        jblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/TriviaGame_Logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jblNickname.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jblNickname.setForeground(new java.awt.Color(255, 255, 255));
        jblNickname.setText("Nickname:");
        getContentPane().add(jblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jblPassword.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(255, 255, 255));
        jblPassword.setText("Password:");
        getContentPane().add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        txtNickname.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        getContentPane().add(txtNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 270, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 270, 40));

        btnLogIn.setBackground(new java.awt.Color(0, 51, 153));
        btnLogIn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Iniciar Sesion");
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogInMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 180, 40));

        jblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/CoolBackground.jpg"))); // NOI18N
        jblBackground.setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().add(jblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseClicked
        // TODO add your handling code here:
        char [] passwordChar = jPasswordField1.getPassword();
        String password = new String (passwordChar);
        String nickname = txtNickname.getText();
        int position = this.myadiministrador.getUserPosition(nickname);
        if (this.myadiministrador.correctInfo(nickname, password)){
            MainMenu myMainMenu = new MainMenu(this.myadiministrador,position);
            myMainMenu.setVisible(true);
        }
    }//GEN-LAST:event_btnLogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Administrador myList = new Administrador();
                new LogIn(myList).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jblBackground;
    private javax.swing.JLabel jblNickname;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JTextField txtNickname;
    // End of variables declaration//GEN-END:variables
}
