package project.windows;

import java.applet.AudioClip;
import project.windows.Menu;
import project.logic.Administrador;
import project.models.User;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    Administrador myadministrador;
    User user;
    AudioClip music;

    public MainMenu(Administrador myList, User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.myadministrador = myList;
        this.user = user;
        music = this.myadministrador.playMusic();
        this.jblNickname.setText("Usuario: " + user.getUserNickname());
        this.jblUserPoints.setText("Puntos: " + (user.getUserPoints()));
        this.jblUserCountry.setText("Pais: " + user.getUserCountry());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jblUserCountry = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jblUserPoints = new javax.swing.JLabel();
        jblNickname = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblUserCountry.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jblUserCountry.setForeground(new java.awt.Color(255, 255, 255));
        jblUserCountry.setText("Pais:");
        getContentPane().add(jblUserCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TriviaGame_Logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 150));

        jblUserPoints.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jblUserPoints.setForeground(new java.awt.Color(255, 255, 255));
        jblUserPoints.setText("Puntos:");
        getContentPane().add(jblUserPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jblNickname.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jblNickname.setForeground(new java.awt.Color(255, 255, 255));
        jblNickname.setText("Usuario:");
        getContentPane().add(jblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        btnStartGame.setBackground(new java.awt.Color(51, 153, 255));
        btnStartGame.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnStartGame.setForeground(new java.awt.Color(255, 255, 255));
        btnStartGame.setText("Iniciar Partida");
        btnStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGameMouseClicked(evt);
            }
        });
        getContentPane().add(btnStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 300, 60));

        btnRanking.setBackground(new java.awt.Color(51, 153, 255));
        btnRanking.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnRanking.setForeground(new java.awt.Color(255, 255, 255));
        btnRanking.setText("Ver Ranking");
        btnRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRankingMouseClicked(evt);
            }
        });
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        getContentPane().add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 300, 60));

        btnExit.setBackground(new java.awt.Color(51, 153, 255));
        btnExit.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 300, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoolBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartGameMouseClicked
        // TODO add your handling code here:
        GameControl mygame = new GameControl(this.myadministrador, 1, this.user);
        mygame.setVisible(true);
        this.myadministrador.stopMusic(music);
        this.dispose();
    }//GEN-LAST:event_btnStartGameMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        Menu menu = new Menu(this.myadministrador);
        menu.setVisible(true);
        this.myadministrador.stopMusic(music);
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRankingMouseClicked
        // TODO add your handling code here:
        Ranking ranking = new Ranking(this.myadministrador, this.user);
        ranking.setVisible(true);
        this.myadministrador.stopMusic(music);
        this.dispose();
    }//GEN-LAST:event_btnRankingMouseClicked

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Administrador myList = new Administrador();
                User user = null;
                new MainMenu(myList, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jblNickname;
    private javax.swing.JLabel jblUserCountry;
    private javax.swing.JLabel jblUserPoints;
    // End of variables declaration//GEN-END:variables
}
